use studyin;

CREATE TABLE `COUNT` 
   (	`TIME` DATE, 
	`PAGEVIEW` int(11), 
	`PAGEVIEWDAY` int(11), 
	`APPLICATION` int(11), 
	`APPLICATIONDAY` int(11), 
	`KAIFAQU` int(11), 
	`ZHIFUQU` int(11), 
	`FUSHANQU` int(11), 
	`MUPINGQU` int(11), 
	`LAISHANQU` int(11), 
	`LONGKOU` int(11), 
	`ZHAOYUAN` int(11), 
	`QIXIA` int(11), 
	`LAIZHOU` int(11), 
	`CHANGDAO` int(11), 
	`HAIYANG` int(11), 
	`LAIYANG` int(11), 
	`PENGLAI` int(11),
       PRIMARY KEY (`TIME`),
  UNIQUE KEY `ordinal_UNIQUE` (`TIME`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
/*

  ALTER TABLE `WYXX`.`COUNT` ADD CONSTRAINT `COUNT_PK` PRIMARY KEY (`TIME`)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE `USERS`  ENABLE;
  ALTER TABLE `WYXX`.`COUNT` MODIFY (`TIME` NOT NULL ENABLE);
*/