use studyin;
CREATE TABLE `ABSTUDY` (
  	`IDCARD` varchar(50 ), 
	`SNAME` varchar(20 ), 
	`LICENCE` varchar(10 ), 
	`TIME` DATE, 
	`SREMARK` varchar(2 ) DEFAULT 0, 
	`PHOTO` varchar(2 ) DEFAULT 1, 
	`PHONENUMBER` varchar(20 ), 
	`DEDUCTPOINTS` varchar(10 ), 
	`LICENCENUMBER` varchar(30 ), 
	`FILENAME` varchar(50 ), 
	`STATUS` varchar(10 ), 
	`DABH` varchar(20 ), 
	`SYYXQZ` DATE, 
	`ERRORCOUNT` int(11), 
	`EXIST` varchar(2 ) DEFAULT 0,
   PRIMARY KEY (`IDCARD`),
  UNIQUE KEY `ordinal_UNIQUE` (`IDCARD`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


/*

  ALTER TABLE `WYXX`.`ABSTUDY` ADD CONSTRAINT `ABSTUDY_PK` PRIMARY KEY (`IDCARD`)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE `USERS`  ENABLE;
  ALTER TABLE `WYXX`.`ABSTUDY` MODIFY (`TIME` NOT NULL ENABLE);
  ALTER TABLE `WYXX`.`ABSTUDY` MODIFY (`DEDUCTPOINTS` NOT NULL ENABLE);
  ALTER TABLE `WYXX`.`ABSTUDY` MODIFY (`PHONENUMBER` NOT NULL ENABLE);
  ALTER TABLE `WYXX`.`ABSTUDY` MODIFY (`LICENCE` NOT NULL ENABLE);
  ALTER TABLE `WYXX`.`ABSTUDY` MODIFY (`SNAME` NOT NULL ENABLE);
  ALTER TABLE `WYXX`.`ABSTUDY` MODIFY (`IDCARD` NOT NULL ENABLE);
*/